<?php

declare(strict_types=1);

namespace Preflow\Routing;

final class RouteCompiler
{
    public function compile(RouteCollection $collection, string $cachePath): void
    {
        $data = $collection->toArray();
        $exported = var_export($data, true);

        $content = "<?php\n\n// Auto-generated by Preflow RouteCompiler. Do not edit.\n// Generated: " . date('Y-m-d H:i:s') . "\n\nreturn {$exported};\n";

        $dir = dirname($cachePath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($cachePath, $content);

        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($cachePath, true);
        }
    }

    public function clear(string $cachePath): void
    {
        if (file_exists($cachePath)) {
            unlink($cachePath);

            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($cachePath, true);
            }
        }
    }
}
